name: Test
on:
  push:

jobs:
  test:
    name: Test
    strategy:
      matrix:
        go-version: [1.13, 1.14]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Test
        run: go test ./...
